### ISSUE TITLE
Improved Fire Totem bug

### ISSUE THREAD

**Issue by acropolles** [MOUZU/TotemTimers-Enhanced#2] opened 2016-12-22 08:07 UTC
Hi, I don't know if you are still working on this but there is a bug that I found, if your character have "Improved fire totem" spec and use fire nova totem the addon reports an error and than stop working.

**Comment by MOUZU** [comment] 2016-12-23 09:29
Hi, thanks for your input. I'll try to take a brief look to see if I can reproduce this issue.

It'd speed up the process if you could quote the exact error message.

**Comment by acropolles** [comment] 2016-12-24 23:20
Sorry for the delay, the message is: Interface\AddOns\TotemTimers.lua:463: attempt to perform arithmetic on field duration' (a nil value)

**Comment by MOUZU** [comment] 2016-12-24 23:46
Thanks for that additional information! I can see the error, this must've already been in the "old retail" version but I'll make the adjustments and upload a new version.

**Comment by acropolles** [comment] 2016-12-24 23:56
Alright, thank you very much.

**Comment by MOUZU** [comment] 2016-12-25 00:26
this fix is included in commit 5701674

**Closed as completed by MOUZU** 2016-12-25 00:26 UTC
Labels: bug

**Comment by Maroej** [comment] 2017-01-25 17:11
Did this bug make you not being able to use healing spells on yourself? Just wondering if its the same problem I have. Started when I switched to Imp. Fire totem and persisting even with fresh WTF and old version of TotemTimers. I am completely confused about what might be causing this

**Comment by MOUZU** [comment] 2017-05-20 13:46
No that can't be caused by this AddOn.
